feat: Add ProductService
KirillFave/s3ng pull request #10
Opened 2024-10-31 13:06 UTC by Berrcir

Добавил ProductService в соответствии с новой структурой проекта

2024-10-31 17:46 UTC, vlivar commented
замечания из https://github.com/KirillFave/s3ng/pull/8 но там вроде не так критично, тыкаю апрув

2024-10-31 17:46 UTC, vlivar approved these changes

2024-11-02 14:57 UTC, KirillFave commented on src/Services/ProductService/DataAccess/Repositories.Implementations/ProductRepository.cs
> +            return await _productSet.FindAsync((object)id);
Вроде, совсем не нужно кастить в object. Guid ведь является объектом

2024-11-02 15:02 UTC, KirillFave commented on src/Services/ProductService/DataAccess/Repositories.Implementations/ProductRepository.cs
> +        public void Update(Product product)
А ты не должен в этом методе вносить изменения? Метод Update только изменяет State, но не меняет сам объект?

2024-11-02 15:04 UTC, KirillFave commented on src/Services/ProductService/ProductService.Host/Controllers/ProductController.cs
> +        [HttpPut("UpdateProduct")]
Не обработаны кейсы 404 NotFound() и 304 NotModified()

2024-11-02 15:05 UTC, KirillFave commented on src/Services/ProductService/ProductService.Host/Controllers/ProductController.cs
> +        public async Task<IActionResult> DeleteAsync(Guid id)
Не обработан кейс 404 NotFound()

2024-11-02 15:07 UTC, KirillFave commented on src/Services/ProductService/ProductService.Host/Controllers/ProductController.cs
> +            return productModel;
Какой HttpCode здесь возвращает? Вроде, нужно явно указать, например:
return orderItem is null ? NotFound() : Ok(orderItem);

2024-11-02 15:07 UTC, KirillFave commented on src/Services/ProductService/ProductService.Host/Controllers/ProductController.cs
> +            return createdProductGuid;
Здесь точно возвращает 204?

2024-11-02 15:08 UTC, KirillFave requested changes
Указал комментами

2024-11-04 15:08 UTC, Berrcir commented on src/Services/ProductService/ProductService.Host/Controllers/ProductController.cs
> +            return createdProductGuid;
Исправил, но остался вопрос об использовании IActionResult

2024-11-04 15:29 UTC, Berrcir commented on src/Services/ProductService/ProductService.Host/Controllers/ProductController.cs
> +            return productModel;
Исправил, но вопрос насчет **NotFound** и **NoContent**. Как будто бы NotFound - ошибка, что ресурса с Api не существует, а не объекта, а вот про объект null иначе. 

Описание ответов и интернета: 

_[204 No Content](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/204)
Для этого запроса нет содержимого для отправки, но заголовки ответа могут быть полезны. Пользовательский агент может использовать их для обновления закешированных заголовков, полученных ранее для этого ресурса.

[404 Not Found](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/404)
Сервер не может найти запрошенный ресурс. В браузере это означает, что URL-адрес не распознан. В API это также может означать, что адрес правильный, но ресурс не существует._

Пока что оставил как NoContent:
**_return productModel is null ? NoContent() : Ok(productModel);_**

2024-11-04 15:58 UTC, Berrcir commented on src/Services/ProductService/ProductService.Host/Controllers/ProductController.cs
> +        public async Task<IActionResult> DeleteAsync(Guid id)
Исправил. Обновил метод Delete до TryDelete (Если есть идеи лучше - с радостью выслушаю). Соответственно появилась проверка с NotFound() - Вопрос использования 404 а не 204. NoContent сюда как будто бы вообще не укладывался

2024-11-04 16:31 UTC, Berrcir commented on src/Services/ProductService/ProductService.Host/Controllers/ProductController.cs
> +        [HttpPut("UpdateProduct")]
Частично исправил. NotFound сделал, но не совсем понял насчет 304. Куда ее и зачем?

2024-11-04 16:33 UTC, Berrcir commented on src/Services/ProductService/DataAccess/Repositories.Implementations/ProductRepository.cs
> +        public void Update(Product product)
В проекте чистого кода из лекции было так. До конца не уверен, как правильнее. Сюда же вопрос - Стоит ли в обновление стейта писать и время обновления ?

product.TimeModified = DateTime.Now;
_productSet.Entry(product).State = EntityState.Modified;

2024-11-04 16:33 UTC, Berrcir commented on src/Services/ProductService/DataAccess/Repositories.Implementations/ProductRepository.cs
> +            return await _productSet.FindAsync((object)id);
Факт, исправил

2024-11-04 16:36 UTC, Berrcir commented on src/Services/ProductService/DataAccess/Repositories.Implementations/ProductRepository.cs
> +        public void Update(Product product)
По идее не требуется, так как работаем с данными как с объектами и меняем объекты, а для апдейта используем SaveChanges()

2024-11-05 14:16 UTC, KirillFave commented on src/Services/ProductService/ProductService.Host/Controllers/ProductController.cs
> +        [HttpPut("UpdateProduct")]
304 - если ты закинул значения свойств такие же, какие они содержатся в БД. Например, если ты захочешь своё имя заменить на "Артур", то тебе должен вернуться NotModified.

2024-11-06 15:59 UTC, KirillFave approved these changes

2024-11-06 16:02 UTC, merged