Init order service
KirillFave/s3ng pull request #13
Opened 2024-11-02 19:04 UTC by KirillFave

2024-11-03 09:33 UTC, vlivar commented on src/Services/OrderService/Controllers/OrderItemController.cs
> +    public OrderItemController(
Для `OrderItem `не нужен метод `Update`?

2024-11-03 09:35 UTC, vlivar commented on src/Services/OrderService/Controllers/OrderController.cs
> +        return result switch
можно вынести в отдельный класс типа `ConverterOperationResult` но это на твоё усмотрение или можно в todo закинуть

2024-11-03 09:39 UTC, vlivar commented on src/Services/OrderService/Models/Order.cs
> +public class Order : BaseEntity
можно добавить `required` для обязательных полей

2024-11-03 09:41 UTC, vlivar commented on src/Services/OrderService/Models/OrderStatus.cs
> +    Draft = 0,
под 0 элементом enum лучше использовать Unspecified или Undefined

2024-11-03 09:41 UTC, vlivar commented on src/Services/OrderService/Models/PaymentType.cs
> +public enum PaymentType
тут тоже можно добавить Unspecified или Undefined

2024-11-03 09:56 UTC, vlivar commented on src/Services/OrderService/OrderService.sln
> +﻿
этот sln нужен? договаривались же в одном делать

2024-11-03 10:02 UTC, vlivar commented
@KirillFave нужно подтянуть main ветку, можно через merge или перебазировать свою ветку через rebase, потому что сейчас залить твою ветку в main без решения конфликтов не получится(

2024-11-04 14:14 UTC, KirillFave commented on src/Services/OrderService/OrderService.sln
> +﻿
Удалил

2024-11-04 14:43 UTC, KirillFave commented on src/Services/OrderService/Controllers/OrderItemController.cs
> +    public OrderItemController(
Не нужен, цена и количество товаров может изменяться в корзине, а когда Order.Status = "Created", то заказ уже оформлен с конкретными значениями. 

Order.Status = "Draft" - это технический статус, который используется для создания заказа. Изначально создаётся заказ "Draft", в него добавляются OrderItem'ы и после этого он переводится в "Created"

2024-11-04 14:44 UTC, KirillFave commented on src/Services/OrderService/Controllers/OrderController.cs
> +        return result switch
Добавил в третий спринт

2024-11-05 13:43 UTC, Berrcir requested changes
Не соблюдена архитектура, с разнесением на слои Core, Services, DataAccess и т. д. Это вроде как должны быть отдельные проекты, а у тебя получается все обо всем знают. Зачем тогда Models и Dto ? Сам OrderService.Host должен быть вынесен как отдельный проект, собирающий в кучу все остальные части сервиса

2024-11-05 13:43 UTC, Berrcir commented on src/Services/OrderService/Controllers/OrderController.cs
> +    }
В качестве репозитория нужно передавать интерфейс на него, а не конкретную реализацию

2024-11-05 13:43 UTC, Berrcir commented on src/Services/OrderService/Controllers/OrderController.cs
> +
Здесь разве требуется указывать, что заказ Nullable? Он же и так класс

2024-11-05 13:43 UTC, Berrcir commented on src/Services/OrderService/Controllers/OrderController.cs
> +        bool result = await _orderRepository.AddAsync(order);
Мне кажется, лучше именовать результатом проверки, а не просто result, так ка что это за результат неясно. Хотя мб вкусовщина (мне больше нравится isOrderCreated/isOrderAdded)

2024-11-05 13:43 UTC, Berrcir commented on src/Services/OrderService/Controllers/OrderController.cs
Контроллер не должен работать с репозиторием. Только с самим сервисом (его интерфейсом). На интерфейс ставится реализация (определяется в Sturtup при подключении сервисов). Никакой логики не следует хранить в контроллере, только вызов методов сервиса. По сути в сервисе нет DI (Dependency Injection) - следует добавить

2024-11-05 14:23 UTC, KirillFave commented on src/Services/OrderService/Controllers/OrderController.cs
> +
Обязательно, иначе CS8600.

2024-11-05 14:49 UTC, Berrcir approved these changes

2024-11-25 08:06 UTC, vlivar commented
в студии сервис не отображается 
![image](https://github.com/user-attachments/assets/fbda3a1f-278f-4202-aa51-04686e21b375)

2024-11-25 08:08 UTC, vlivar commented
кажется уже кто-то спрашивал но я забыл, зачем это?
![image](https://github.com/user-attachments/assets/086e7dbb-a47f-42ba-be4f-7ccea19b976b)

2024-11-25 16:12 UTC, KirillFave commented
Замечания Влада учёл. Файлы WWW ошибочно вернулись, когда делал rebase, видимо. Проект привязал к общему sln

2024-11-25 16:49 UTC, vlivar approved these changes

2024-11-28 15:54 UTC, merged