Feature: DeliveryService Created
KirillFave/s3ng pull request #17
Opened 2024-12-10 08:04 UTC by Dmitrypon

DeliveryService: 
Содержит базовый функционал сервиса

2024-12-10 14:55 UTC, vlivar commented
нужно сделать merge main ветки основного репозитория

2024-12-10 14:55 UTC, vlivar commented on src/CreateDeliveryDTO.cs
> +public class Class1
что за класс `Class1`? зачем это?

2024-12-10 14:56 UTC, vlivar commented on src/DeliveryDTO.cs
> +public class Class1
что за класс `Class1`? зачем это?

2024-12-10 14:56 UTC, vlivar commented on src/CreateDeliveryItemDTO.cs
> +	{
поехало форматирование

2024-12-10 14:59 UTC, vlivar commented on src/Services/DeliveryService/Repositories/DeliveryRepository.cs
> +        /// Получить сущность по AuthenticationId.
не совсем понимаю зачем сущности `Delivery` нужен `AuthenticationId`
Нужен?

2024-12-10 15:01 UTC, vlivar commented on src/Services/DeliveryService/Repositories/DeliveryRepository.cs
> +        /// Для сущности проставить состояние - что она изменена.
этот метод только проставляет состояние Modified?
так надо? зачем?

2024-12-10 15:03 UTC, vlivar commented on src/Services/DeliveryService/Repositories/DeliveryRepository.cs
> +        public Task<Delivery> GetByIdAsync(Guid guid)
зачем этот и другие методы ниже с NotImplementedException? 
будут реализованы? вроде уже есть такие выше

2024-12-10 15:05 UTC, vlivar commented on src/Services/DeliveryService/Controllers/DeliveryController.cs
> +        public async Task<ActionResult> Create(Delivery delivery)
в этом методе или в методе контроллера `AddAsync` не нужен `SaveChangesAsync` ?

2024-12-10 15:05 UTC, vlivar commented on src/Services/DeliveryService/Controllers/DeliveryController.cs
> +        public async Task<ActionResult> Update(Delivery delivery)
в этом методе или в методе контроллера UpdateAsync не нужен SaveChangesAsync ?

2024-12-10 15:06 UTC, vlivar commented on src/Services/DeliveryService/Controllers/DeliveryController.cs
> +            OperationResults result = await _deliveryRepository.DeleteAsync(guid);
так же для del вызывается где то SaveChangesAsync?

2024-12-10 15:07 UTC, vlivar commented on src/Services/DeliveryService/Controllers/DeliveryController.cs
> +            OperationResults result = await _deliveryRepository.DeleteAsync(guid);
вызывается не реализованный в репозитории метод

2024-12-10 15:08 UTC, vlivar commented on src/Services/DeliveryService/Controllers/DeliveryController.cs
> +            OperationResults result = await _deliveryRepository.UpdateAsync(delivery);
вызывается не реализованный в репозитории метод

2024-12-10 15:10 UTC, vlivar commented on src/Services/DeliveryService/DTO/CreateDeliveryDTO.cs
> +    public class CreateDeliveryDTO
на будущее надо подумать над составам полей

2024-12-10 15:12 UTC, vlivar commented on src/Services/DeliveryService/DTO/DeliveryDTO.cs
> +public class DeliveryDTO
дублирует CreateDeliveryDTO ,можно сделать базовый класс с основыми сущностями и наследоваться от него, тогда тут появится лишь Delivery_Time

2024-12-10 15:12 UTC, vlivar commented on src/Services/DeliveryService/DTO/DeliveryDTO.cs
> +public class DeliveryDTO
и думаю тут не хватает статуса по доставке

2024-12-10 15:13 UTC, vlivar commented on src/Services/DeliveryService/DTO/GetDeliveryResponse.cs
> +    public class GetDeliveryResponse
так же большое дублирование DeliveryDTO, см комент там

2024-12-10 15:14 UTC, vlivar commented on src/Services/DeliveryService/DTO/UpdateDeliveryDTO.cs
> +    public class UpdateDeliveryDTO
тоже дублирование, можно поправить позже всё это

2024-12-10 15:16 UTC, vlivar commented on src/Services/DeliveryService/DeliveryService.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
вроде договаривались без отдельных sln, нужно убрать видимо

2024-12-10 15:18 UTC, vlivar commented on src/Services/DeliveryService/Dockerfile
> +EXPOSE 8080
поменять, будут конфликты с ProductService у него тоже 8080

2024-12-10 15:19 UTC, vlivar commented on src/Services/DeliveryService/Domain/Domain.Entities/Courier.cs
> +        public virtual Delivery Delivery { get; set; }
один курьер не может иметь несколько доставок?

2024-12-10 15:20 UTC, vlivar commented on src/Services/DeliveryService/Domain/Domain.Entities/Courier.cs
> +        public virtual Delivery Delivery { get; set; }
`Shipping_Address` может быть внутри Delivery

2024-12-10 15:20 UTC, vlivar commented on src/Services/DeliveryService/Domain/Domain.Entities/Delivery.cs
> +    public class Delivery : IEntity<Guid>
как и писал выше - надо подумать над полями

2024-12-10 15:21 UTC, vlivar commented on src/Services/DeliveryService/Domain/Domain.Entities/Route.cs
> +    public class Route : IEntity<Guid>
это зачем?

2024-12-15 03:46 UTC, KirillFave commented on src/Services/DeliveryService/Repositories/DeliveryRepository.cs
> +        /// Получить сущность по AuthenticationId.
Там должен быть UserId, как я понимаю

2024-12-15 03:49 UTC, KirillFave commented on src/Services/DeliveryService/DTO/CreateDeliveryDTO.cs
> +    public class CreateDeliveryDTO
Не хватает поля со статусом доставки

2024-12-15 12:46 UTC, romaib116 requested changes
Согласен с замечаниями Влада

2024-12-17 07:38 UTC, Dmitrypon commented on src/Services/DeliveryService/Repositories/DeliveryRepository.cs
> +        /// Получить сущность по AuthenticationId.
Кирилл прав, должен быть userId

2024-12-17 07:55 UTC, Dmitrypon commented on src/Services/DeliveryService/Repositories/DeliveryRepository.cs
> +        /// Для сущности проставить состояние - что она изменена.
Конечно нет. Исправляю - >
Должно отразить изменение:
- CourierId;
-  Shipping_Address;
- Estimated_Delivery_Time;
- List<OrderItem>;
- Total_Quanti;
- Total_Price;
- PaymentType.

2024-12-17 07:56 UTC, Dmitrypon commented on src/DeliveryDTO.cs
> +public class Class1
Удалил

2024-12-17 07:56 UTC, Dmitrypon commented on src/CreateDeliveryDTO.cs
> +public class Class1
Удалил

2024-12-17 08:00 UTC, Dmitrypon commented on src/Services/DeliveryService/Dockerfile
> +EXPOSE 8080
Изменил на 8090

2024-12-17 08:02 UTC, Dmitrypon commented on src/Services/DeliveryService/Domain/Domain.Entities/Courier.cs
> +        public virtual Delivery Delivery { get; set; }
Delivery:

 [Required]
 public virtual List<Courier> ? Couriers { get; set; }

2024-12-17 08:04 UTC, Dmitrypon commented on src/Services/DeliveryService/Domain/Domain.Entities/Route.cs
> +    public class Route : IEntity<Guid>
Исправил

2024-12-17 11:32 UTC, Dmitrypon commented on src/Services/DeliveryService/DTO/GetDeliveryResponse.cs
> +    public class GetDeliveryResponse
Удалил DeliveryDTO, изменил CreateDeliveryDTO.

2024-12-17 11:34 UTC, Dmitrypon commented on src/Services/DeliveryService/DeliveryService.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
Будет уничтожен.

2024-12-18 02:35 UTC, Dmitrypon commented on src/CreateDeliveryItemDTO.cs
> +	{
Исправил

2024-12-19 09:31 UTC, Dmitrypon commented on src/CreateDeliveryItemDTO.cs
> +	{
class CreateDeliveryItemDTO удален

2024-12-19 09:47 UTC, Dmitrypon commented on src/Services/DeliveryService/Repositories/DeliveryRepository.cs
> +        /// Для сущности проставить состояние - что она изменена.
Указал поля для Update

2024-12-19 09:54 UTC, Dmitrypon commented on src/Services/DeliveryService/Repositories/DeliveryRepository.cs
> +        public Task<Delivery> GetByIdAsync(Guid guid)
NotImplementedException удалил, изменил DeliveryRepository, Models добавил, дополнил  DeliveryMappingProfile.

2024-12-19 09:59 UTC, Dmitrypon commented on src/Services/DeliveryService/Controllers/DeliveryController.cs
> +        public async Task<ActionResult> Create(Delivery delivery)
DeliveryRepository - 155 line: int stateEntriesWritten = await Context.SaveChangesAsync();

2024-12-19 10:03 UTC, Dmitrypon commented on src/Services/DeliveryService/Controllers/DeliveryController.cs
> +        public async Task<ActionResult> Update(Delivery delivery)
HttpPatch удалил, в контроллере метод HttPut("UpdateDelivery").

2024-12-19 10:08 UTC, Dmitrypon commented on src/Services/DeliveryService/Controllers/DeliveryController.cs
> +            OperationResults result = await _deliveryRepository.DeleteAsync(guid);
DeliveryRepository.DeleteAsync дописал await Context.SaveChangesAsync();

2024-12-19 10:12 UTC, Dmitrypon commented on src/Services/DeliveryService/Controllers/DeliveryController.cs
> +            OperationResults result = await _deliveryRepository.DeleteAsync(guid);
В DeliveryRepository реализовал

2024-12-19 10:13 UTC, Dmitrypon commented on src/Services/DeliveryService/Controllers/DeliveryController.cs
> +            OperationResults result = await _deliveryRepository.UpdateAsync(delivery);
Изменил, реализовал

2024-12-19 10:13 UTC, Dmitrypon commented on src/Services/DeliveryService/DTO/CreateDeliveryDTO.cs
> +    public class CreateDeliveryDTO
Изменил состав полей, надо еще проверить

2024-12-19 10:14 UTC, Dmitrypon commented on src/Services/DeliveryService/DTO/DeliveryDTO.cs
> +public class DeliveryDTO
DeliveryStatus добавил

2024-12-19 10:17 UTC, Dmitrypon commented on src/Services/DeliveryService/Domain/Domain.Entities/Delivery.cs
> +    public class Delivery : IEntity<Guid>
Позднее еще раз проверю

2024-12-19 12:54 UTC, Dmitrypon reviewed
По всем замечаниям внес модификации

2024-12-21 17:41 UTC, KirillFave commented on src/CreateDeliveryDTO.cs
> +public class Class1
Ты либо не удалил, либо не запушил изменения в своей ветке

2024-12-21 17:41 UTC, KirillFave commented on src/DeliveryDTO.cs
> +public class Class1
Ты либо не удалил, либо не запушил изменения в своей ветке

2024-12-21 17:41 UTC, KirillFave commented on src/CreateDeliveryItemDTO.cs
> +	{
Ты либо не удалил, либо не запушил изменения в своей ветке

2024-12-22 09:45 UTC, vlivar commented on src/CreateDeliveryDTO.cs
> +public class Class1
![image](https://github.com/user-attachments/assets/ffce6da1-247f-4fb2-8e0d-1875bc381c20)
эти файлы ещё в проекте, нужно удалить их в папке

2024-12-22 09:46 UTC, vlivar commented on src/CreateDeliveryItemDTO.cs
> +	{
эти файлы ещё в проекте, нужно удалить их в папке
см скрин в комменте выше

2024-12-22 09:46 UTC, vlivar commented on src/DeliveryDTO.cs
> +public class Class1
эти файлы ещё в проекте, нужно удалить их в папке
см скрин в комменте выше

2024-12-22 09:47 UTC, vlivar commented on src/Services/DeliveryService/DeliveryService.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
файл не уничтожен

2024-12-22 09:49 UTC, vlivar commented on src/Services/DeliveryService/Repositories/DeliveryRepository.cs
> +        public virtual bool Delete(Delivery entity)
тут не нужен SaveChanges?

2024-12-22 09:49 UTC, vlivar commented on src/Services/DeliveryService/Repositories/DeliveryRepository.cs
> +        public virtual bool DeleteRange(ICollection<Delivery> entities)
тут не нужен SaveChanges?

2024-12-22 09:50 UTC, vlivar commented on src/Services/DeliveryService/Repositories/DeliveryRepository.cs
> +        public async Task<Delivery> AddAsync(Delivery delivery, CancellationToken cancellationToken)
тут не нужен SaveChanges?

2024-12-22 09:50 UTC, vlivar commented on src/Services/DeliveryService/Repositories/DeliveryRepository.cs
> +        public virtual void AddRange(List<Delivery> entities)
тут не нужен SaveChanges?

2024-12-22 09:52 UTC, vlivar commented
@Dmitrypon посмотри новый комменты, удали лишние файлы, сделай снова merge main и можно будет заливать

2024-12-23 08:45 UTC, Dmitrypon reviewed
New changes

2024-12-24 06:56 UTC, vlivar approved these changes
ставлю апрув но файл DeliveryService.sln ещё не удален

2025-03-25 16:38 UTC, closed without merging