feat [OrderService]: WebHost controllers + docker file
KirillFave/s3ng pull request #20
Opened 2024-12-15 05:52 UTC by KirillFave

2024-12-15 09:35 UTC, vlivar commented
не прошел билд ci, скорей всего есть errors в коде
нужно втянуть main в ветку

2024-12-15 09:44 UTC, vlivar commented on src/docker-compose.yml
> +      - "5066:5066"
в докер файле order сервиса порты надо поправить
![image](https://github.com/user-attachments/assets/19eee5d8-1e67-45ca-96fe-84daa13812b9)

2024-12-15 09:47 UTC, vlivar commented
Может бд на postgre заменишь? могу рассказать как что

2024-12-15 12:46 UTC, romaib116 requested changes
CI падает, а в целом норм

2024-12-15 12:46 UTC, romaib116 commented on src/ApiGateway/WebHost/Controllers/OrderController.cs
> +﻿using Microsoft.AspNetCore.Mvc;
кодировка

2024-12-18 17:55 UTC, vlivar commented on src/ApiGateway/WebHost/WebHost.csproj
> +    <ProjectReference Include="..\..\Services\OrderService\OrderService.csproj" />
не должно быть такой зависимости от проекта Services

2025-01-09 04:51 UTC, romaib116 approved these changes

2025-01-23 12:55 UTC, vlivar approved these changes

2025-01-26 13:45 UTC, merged