feat: add user service
KirillFave/s3ng pull request #6
Opened 2024-10-07 17:54 UTC by vlivar

2024-10-07 19:19 UTC, danilaPhysch commented on UserService/EFCore/Configuration.cs
> +        var connectionString = $"Host={configuration["USER_SERVICE_POSTGRES_HOST"] ?? "localhost"};" +
Мне кажется, что падение приложения при незаданной конфигурации - более предпочтительное поведение

2024-10-07 19:20 UTC, danilaPhysch commented on UserService/EFCore/Configuration.cs
> +        var ff = configuration["USER_SERVICE_URI"];
Не используется

2024-10-07 19:24 UTC, danilaPhysch commented on UserService/Program.cs
> +builder.WebHost.ConfigureKestrel(options =>
А для чего это используется?

2024-10-07 19:25 UTC, danilaPhysch commented on UserService/Program.cs
> +    options.ListenAnyIP(5005, listenOptions => listenOptions.Protocols = HttpProtocols.Http2);
Тем более, хардкодить порт не очень хорошо. Лучше вынести в конфиг

2024-10-10 18:50 UTC, romaib116 requested changes
вопросы только по реквизитному составу юзера

2024-10-10 18:50 UTC, romaib116 commented on UserService/EFCore/Entities/User.cs
> +    public required string Login { get; set; }
точно стоит хранить логин? я его тоже храню, мы можем с тобой вязаться по ИДу

2024-10-10 18:50 UTC, romaib116 commented on UserService/EFCore/Entities/User.cs
> +    public required string PasswordHash { get; set; }
И хэш пароля я тоже храню, т.к. авторизация и регистрация у меня. Вроде как мы можем просто по ИДшнику с тобой болтать

2024-10-11 06:05 UTC, vlivar commented on UserService/EFCore/Entities/User.cs
> +    public required string Login { get; set; }
у меня по бд есть пару вопросов, в том числе про это) 
постараюсь в ближайшее время сформулировать и отписаться в канал

2024-10-13 08:55 UTC, vlivar commented on UserService/Program.cs
> +builder.WebHost.ConfigureKestrel(options =>
для определения версии протокола http при работе с grpc нужна версия - `HttpProtocols.Http2`

2024-10-13 08:58 UTC, vlivar commented on UserService/Program.cs
> +    options.ListenAnyIP(5005, listenOptions => listenOptions.Protocols = HttpProtocols.Http2);
согласен, можно

2024-10-13 09:00 UTC, vlivar commented on UserService/EFCore/Configuration.cs
> +        var connectionString = $"Host={configuration["USER_SERVICE_POSTGRES_HOST"] ?? "localhost"};" +
Да, тут надо будет подумать ещё

2024-10-29 14:20 UTC, romaib116 approved these changes

2024-10-29 14:21 UTC, Berrcir approved these changes

2024-10-29 14:21 UTC, merged